version: 0.0
os: linux
files:
  - source: ChickenCoop-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/coop
  - source: tables.sql
    destination: /home/ec2-user/coop
  - source: createtables.sh
    destination: /home/ec2-user/coop
  - source: start.sh
    destination: /home/ec2-user/coop
  - source: shutdown.sh
    destination: /home/ec2-user/coop
hooks:
  AfterInstall:
    - location: createtables.sh
      timeout: 300
  ApplicationStart:
    - location: start.sh
      timeout: 300
  ApplicationStop:
    - location: shutdown.sh
      timeout: 300