version: 0.0
os: linux
files:
  - source: ChickenCoop-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/coop
hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 300
  ApplicationStop:
    - location: shutdown.sh
      timeout: 300