version: 0.0
os: linux
files:
  - source: target/ChickenCoop-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/coop
  - source: sql/
    destination: /home/ec2-user/coop/sql
  - source: scripts/aws/createtables.sh
    destination: /home/ec2-user/coop
  - source: scripts/aws/start.sh
    destination: /home/ec2-user/coop
  - source: scripts/aws/shutdown.sh
    destination: /home/ec2-user/coop
  - source: shutdown.sh
    destination: /home/ec2-user/coop
hooks:
  AfterInstall:
    - location: scripts/aws/createtables.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/aws/start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/aws/shutdown.sh
      timeout: 300