ALTER TABLE `rule_execution_log`
	DROP FOREIGN KEY `RULE_EXECUTION_LOG_FK1`;

ALTER TABLE `rule_execution_log`
	ADD CONSTRAINT `RULE_EXECUTION_LOG_FK1` FOREIGN KEY (`RULE_ID`) REFERENCES `rule` (`RULE_ID`) ON DELETE CASCADE;
