CREATE TABLE IF NOT EXISTS `rule_execution_log` (
	`ID` VARCHAR(32) NOT NULL,
	`RULE_ID` VARCHAR(32) NOT NULL,
	`CREATED_AT` BIGINT NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `RULE_EXECUTION_LOG_FK1` FOREIGN KEY (`RULE_ID`) REFERENCES `rule` (`RULE_ID`),
	INDEX (`RULE_ID`)
);
