CREATE TABLE IF NOT EXISTS `component_ports` (
	`COMPONENT_ID` VARCHAR(32) NOT NULL,
	`PORT_INDEX` INT NOT NULL,
	`NAME` VARCHAR(128) NOT NULL,
	PRIMARY KEY (`COMPONENT_ID`, `PORT_INDEX`),
	CONSTRAINT `COMPONENT_PORTS_FK1` FOREIGN KEY (`COMPONENT_ID`) REFERENCES `components` (`COMPONENT_ID`),
	INDEX (`COMPONENT_ID`)
);
