 CREATE TABLE IF NOT EXISTS `rule_trigger_time` (
 	`RULE_TRIGGER_TIME_ID` VARCHAR(32) NOT NULL,
	`RULE_ID` varchar(32) NOT NULL,
    `HOUR` INT NOT NULL,
    `MINUTE` INT NOT NULL,
    `OPERATOR` VARCHAR(32) NOT NULL,

    PRIMARY KEY (`RULE_TRIGGER_TIME_ID`),
    CONSTRAINT `RULE_TRIGGER_TIME_FK1` FOREIGN KEY (`RULE_ID`) REFERENCES `rule` (`RULE_ID`) ON DELETE CASCADE
 );
