CREATE TABLE IF NOT EXISTS `port_action_log` (
	`ID` VARCHAR(32) NOT NULL,
	`COMPONENT_ID` VARCHAR(32) NOT NULL,
	`PORT_INDEX` INT NOT NULL,
	`ACTION_KEY` VARCHAR(32) NOT NULL,
	`SOURCE` VARCHAR(16) NULL,
	`STATUS` VARCHAR(16) NOT NULL,
	`CREATED_AT` BIGINT NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `PORT_ACTION_LOG_FK1` FOREIGN KEY (`COMPONENT_ID`) REFERENCES `components` (`COMPONENT_ID`),
	INDEX (`COMPONENT_ID`, `PORT_INDEX`)
);
