CREATE TABLE IF NOT EXISTS area (
    AREA_ID           VARCHAR(32) NOT NULL,
    COOP_ID           VARCHAR(32) NOT NULL,
    PARENT_AREA_ID    VARCHAR(32),
    NAME              VARCHAR(128) NOT NULL,
    TYPE              VARCHAR(32) NOT NULL,

    PRIMARY KEY (AREA_ID),
    KEY idx_area_coop (COOP_ID),

    CONSTRAINT AREA_FK1
    FOREIGN KEY (COOP_ID) REFERENCES coops (COOP_ID) ON DELETE CASCADE,

    CONSTRAINT AREA_FK2
    FOREIGN KEY (PARENT_AREA_ID) REFERENCES area (AREA_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS area_component (
    AREA_ID           VARCHAR(32) NOT NULL,
    COMPONENT_ID      VARCHAR(32) NOT NULL,

    PRIMARY KEY (AREA_ID, COMPONENT_ID),

    CONSTRAINT AREA_COMPONENT_FK1
    FOREIGN KEY (AREA_ID) REFERENCES area (AREA_ID) ON DELETE CASCADE,

    CONSTRAINT AREA_COMPONENT_FK2
    FOREIGN KEY (COMPONENT_ID) REFERENCES components (COMPONENT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS area_component_port (
    AREA_ID           VARCHAR(32) NOT NULL,
    COMPONENT_ID      VARCHAR(32) NOT NULL,
    PORT_INDEX        INT NOT NULL,

    PRIMARY KEY (AREA_ID, COMPONENT_ID, PORT_INDEX),

    CONSTRAINT AREA_COMPONENT_PORT_FK1
    FOREIGN KEY (AREA_ID) REFERENCES area (AREA_ID) ON DELETE CASCADE,

    CONSTRAINT AREA_COMPONENT_PORT_FK2
    FOREIGN KEY (COMPONENT_ID, PORT_INDEX) REFERENCES component_ports (COMPONENT_ID, PORT_INDEX) ON DELETE CASCADE
);
