USE PI_STATE;

CREATE TABLE IF NOT EXISTS rule_trigger_state (

    RULE_ID VARCHAR(32) NOT NULL,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_STATE_DT BIGINT NOT NULL,

    PRIMARY KEY (RULE_ID)
);