USE coop;

CREATE TABLE IF NOT EXISTS `users` (
    `USER_ID` varchar(32) NOT NULL,
    `USERNAME` varchar(128) NOT NULL,
    `PASSWORD` varchar(128) NOT NULL,
    `ENABLED` tinyint(1) NOT NULL,
    PRIMARY KEY (`USER_ID`),
    UNIQUE KEY `USERNAME` (`USERNAME`)
 );

CREATE TABLE IF NOT EXISTS `authorities` (
	`AUTHORITY_ID` MEDIUMINT NOT NULL AUTO_INCREMENT,
    `USER_ID` varchar(128) NOT NULL,
    `AUTHORITY` varchar(128) NOT NULL,
    PRIMARY KEY (`AUTHORITY_ID`),
    UNIQUE KEY `AUTHORITIES_UNIQUE` (`USER_ID`,`AUTHORITY`),
    CONSTRAINT `AUTHORITIES_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`)
 );
 
 
CREATE TABLE IF NOT EXISTS `coops` (
	`COOP_ID` varchar(32) NOT NULL,
    `USER_ID` varchar(128) NOT NULL,
    `NAME` varchar(128) NOT NULL,
    PRIMARY KEY (`COOP_ID`),
    CONSTRAINT `COOPS_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`)
 );

select * from coops;